# Generated by Django 5.1.1 on 2025-01-01 01:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='hotels', verbose_name='عکس هتل')),
                ('name', models.CharField(max_length=255, verbose_name='نام هتل')),
                ('star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='ستاره')),
                ('swim', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='استخر شنا')),
                ('gym', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='باشگاه')),
                ('wifi', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='wi-fi')),
                ('roomsevice', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='سرویس اتاق')),
                ('aircondition', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='تهویه هوا')),
                ('resturant', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=False, verbose_name='رستوران')),
                ('price', models.IntegerField(verbose_name='قیمت برای هر شب')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل ها',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travels', models.IntegerField(verbose_name='تعداد سفرها')),
                ('clients', models.IntegerField(verbose_name='تعداد مشتری ها')),
                ('employees', models.IntegerField(verbose_name='تعداد کارمندان')),
                ('countries', models.IntegerField(verbose_name='تعداد کشورها')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات',
            },
        ),
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='نام')),
                ('last_name', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=250, verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیام کاربر',
                'verbose_name_plural': 'پیام های کاربران',
            },
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام مکان')),
                ('avatar', models.ImageField(upload_to='slides')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='testimonials')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'توصیفات',
                'verbose_name_plural': 'توصیفات',
            },
        ),
        migrations.CreateModel(
            name='WriterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='writers')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('semat', models.CharField(max_length=255, verbose_name='سمت')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='blogs')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='توضیحات')),
                ('short', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='پیش نمایش')),
                ('time', models.DateField(auto_now=True)),
                ('tags', models.TextField(blank=True, null=True, verbose_name='تگ ها(تگ های مورد نظر را با استفاده از کاما از یکدیگر جدا کنید)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahra.category')),
                ('writers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahra.writermodel')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='special')),
                ('keshvar', models.CharField(max_length=250, verbose_name='نام کشور')),
                ('makan', models.CharField(max_length=250, verbose_name='نام مکان')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahra.blogmodel', verbose_name='مقاله مرتبط')),
            ],
            options={
                'verbose_name': 'مقصد محبوب',
                'verbose_name_plural': 'مقاصد محبوب',
            },
        ),
        migrations.CreateModel(
            name='SpecialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='special')),
                ('keshvar', models.CharField(max_length=250, verbose_name='نام کشور')),
                ('makan', models.CharField(max_length=250, verbose_name='نام مکان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahra.blogmodel', verbose_name='مقاله مرتبط')),
            ],
            options={
                'verbose_name': 'آفر ویژه',
                'verbose_name_plural': 'آفر های ویژه',
            },
        ),
        migrations.CreateModel(
            name='VisaDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='visa')),
                ('keshvar', models.CharField(max_length=250, verbose_name='نام کشور')),
                ('makan', models.CharField(max_length=250, verbose_name='نوع ویزا')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahra.blogmodel', verbose_name='مقاله مرتبط')),
            ],
            options={
                'verbose_name': 'ویزا',
                'verbose_name_plural': 'ویزا ها',
            },
        ),
    ]
