# Generated by Django 5.1.1 on 2024-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='special')),
                ('keshvar', models.CharField(max_length=250, verbose_name='نام کشور')),
                ('makan', models.CharField(max_length=250, verbose_name='نام مکان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'آفر های ویژه',
            },
        ),
        migrations.AlterModelOptions(
            name='slidermodel',
            options={'verbose_name': 'اسلاید ها'},
        ),
    ]
